name: savitri_app
description: "AI-powered psychology therapy app providing accessible mental health support"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  provider: ^6.1.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI/UX dependencies
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  flutter_animate: ^4.3.0
  
  # Audio and Voice
  permission_handler: ^11.0.1
  record: ^5.0.4
  audioplayers: ^5.2.1
  
  # Authentication
  local_auth: ^2.1.7
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  
  # WebView for live-audio integration
  webview_flutter: ^4.4.2
  
  # Machine Learning
  tflite_flutter: ^0.10.4
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Utilities
  uuid: ^4.2.2
  intl: ^0.18.1
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/models/
  
  # fonts:
  #   - family: SFProDisplay
  #     fonts:
  #       - asset: assets/fonts/SF-Pro-Display-Regular.otf
  #       - asset: assets/fonts/SF-Pro-Display-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/SF-Pro-Display-Bold.otf
  #         weight: 700
